create database blinkit;

use blinkit;

select * from blinkit_dataset limit 15;   

describe blinkit_dataset;

select count(*) As Total_Products from blinkit_dataset; -- total product

select distinct category from blinkit_dataset;  -- all product category

select product_name,rating from blinkit_dataset where rating > 4;  -- product with rating greater than 4

select product_name, price  from blinkit_dataset order by price desc limit 10; -- top 10 expensive product

select category , avg(price) as avg_price from blinkit_dataset group by category; -- avr price of product in each category

SELECT category, SUM(sold_quantity) AS Total_Sales FROM blinkit_dataset GROUP BY category; -- total sales quantity for each category

SELECT product_name, stock, reorder_level FROM blinkit_dataset WHERE stock > reorder_level; -- products whose stock is below the reorder level

SELECT product_name, sold_quantity FROM blinkit_dataset ORDER BY sold_quantity DESC LIMIT 10; -- top 10 best-selling products

SELECT city, SUM(final_price * sold_quantity) AS Revenue FROM blinkit_dataset GROUP BY city; -- total revenue generated by each city

SELECT category, AVG(rating) AS Avg_Rating FROM blinkit_dataset GROUP BY category; -- average rating for each category

SELECT product_name, profit_margin_pct
FROM blinkit_dataset
ORDER BY profit_margin_pct DESC
LIMIT 1;  -- product with the highest profit margin

SELECT delivery_status, COUNT(*) AS Product_Count
FROM blinkit_dataset
GROUP BY delivery_status; -- number of products under each delivery status

SELECT brand, SUM(sold_quantity) AS Total_Sales
FROM blinkit_dataset
GROUP BY brand
ORDER BY Total_Sales DESC
LIMIT 5; -- top 5 brands based on sales quantity

SELECT product_name, sold_quantity,
       DENSE_RANK() OVER(
       ORDER BY sold_quantity DESC
       ) AS Sales_Rank
FROM blinkit_dataset; -- Rank products based on sold quantity

SELECT category, SUM(final_price * sold_quantity) AS Revenue
FROM blinkit_dataset
GROUP BY category
ORDER BY Revenue DESC; -- categories generating the highest revenue

SELECT brand, SUM(discount_pct) AS Total_Discount
FROM blinkit_dataset
GROUP BY brand; -- Calculate total discount offered by each brand

SELECT product_name
FROM blinkit_dataset
WHERE is_organic = TRUE; -- products that are marked as organic

SELECT product_name, expiry_date
FROM blinkit_dataset
WHERE expiry_date <= CURDATE() + INTERVAL 30 DAY; -- products expiring within the next 30 days

SELECT city, AVG(delivery_time_min) AS Avg_Delivery_Time
FROM blinkit_dataset
GROUP BY city
ORDER BY Avg_Delivery_Time DESC
LIMIT 1; -- city with the highest average delivery time

SELECT category, SUM(stock) AS Total_Stock
FROM blinkit_dataset
GROUP BY category; -- Compare stock availability across categories

SELECT product_name, demand_index
FROM blinkit_dataset
WHERE demand_index > 80; -- products with demand index greater than 80

SELECT seller, SUM(final_price * sold_quantity) AS Revenue
FROM blinkit_dataset
GROUP BY seller; -- revenue generated by each seller

SELECT product_name, num_reviews
FROM blinkit_dataset
WHERE num_reviews > 100; -- products having more than 100 reviews

SELECT packaging_type, COUNT(*) AS Total_Products
FROM blinkit_dataset
GROUP BY packaging_type
ORDER BY Total_Products DESC
LIMIT 1; -- Determine the most popular packaging type

SELECT MONTH(date_added) AS Month, COUNT(*) AS Products_Added
FROM blinkit_dataset
GROUP BY MONTH(date_added)
ORDER BY Month; -- monthly product additions using date_added

SELECT category, AVG(shelf_life_days) AS Avg_Shelf_Life
FROM blinkit_dataset
GROUP BY category; -- average shelf life by category

SELECT product_name, stock
FROM blinkit_dataset
WHERE stock = 0; -- products with zero stock

SELECT brand, AVG(rating) AS Avg_Rating
FROM blinkit_dataset
GROUP BY brand
ORDER BY Avg_Rating DESC; -- brands with the highest average ratings

SELECT category, SUM((final_price * sold_quantity) * (profit_margin_pct/100)) AS Profit
FROM blinkit_dataset
GROUP BY category; -- profit generated by each category